version: '2'
services:
  webserver:
    image: nginx:latest
    container_name: webserverbot
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/www:/var/www
      - ./ssl/:/etc/ssl/nginx/
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
  bot-appss:
    image: i2cmx/atebot:${BOT_TAG}
    environment:
      - MONGO_URI=mongodb://kbase-db:27017
      - MONGO_KB_URI=mongodb://kbase-db:27017/chatbot
      - NODE_ENV=${BOT_ENV}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DB=${DB_NAME}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=America/Mexico_City
    ports:
      - 8085:3000
    depends_on:
    - kbase-db
  kbase-apps:
    container_name: 'kbase-app'
    image: i2cmx/kbase:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://kbase-db:27017
      - SPRING_DATA_MONGODB_DATABASE=chatbot
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    depends_on:
    - kbase-db
    - vtiger-db
  kbase-db:
    container_name: 'kbase-db'
    image: mongo:3.6.14
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  vtiger-db:
    container_name: 'vtiger-db'
    image: mysql:5.6.23
    volumes:
      - ./data/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql/db:/var/lib/mysql
    env_file:
      - ./data/mysql/env
    ports:
      - 3306:3306