version: '2'
services:
  bot-app:
    image: i2cmx/atebot:${BOT_TAG}
    environment:
      - MONGO_URI=mongodb://bot-mongodb:27017
      - MONGO_KB_URI=mongodb://bot-mongodb:27017/chatbot
      - NODE_ENV=${BOT_ENV}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DB=${DB_NAME}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=America/Mexico_City
    ports:
      - 8085:3000
    depends_on:
    - bot-mongodb
  kbase-app:
    image: i2cmx/kbase:${KBASE_TAG}
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
      - SPRING_DATA_MONGODB_URI=mongodb://bot-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=chatbot
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    depends_on:
    - bot-mongodb
  bot-mongodb:
    image: mongo:3.6.14
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
