version: '3.3'
services:
  bot-app:
    image: i2cmx/atebot:${TAG}
    environment:
      - MONGO_URI=mongodb://bot-mongodb:27017
      - CONTEXT=docker
    ports:
      - 8085:3000
    depends_on:
    - bot-mongodb
  bot-mongodb:
    image: mongo:3.6.14
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
