version: '2'
services:
  bot-app:
    container_name: 'bot-app'
    image: i2cmx/atebot:latest
    environment:
      - MONGO_URI=mongodb://kbase-db:27017
      - MONGO_KB_URI=mongodb://kbase-db:27017/chatbot
      - NODE_ENV=${BOT_ENV}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DB=${DB_NAME}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 8090:3000
    depends_on:
    - kbase-app
  kbase-app:
    container_name: 'kbase-app'
    image: i2cmx/kbase:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
      - SPRING_DATA_MONGODB_URI=mongodb://kbase-db:27017
      - SPRING_DATA_MONGODB_DATABASE=chatbot
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8091:8080
    depends_on:
    - kbase-db
    - vtiger-db
  kbase-db:
    container_name: 'kbase-db'
    image: mongo:3.6.14
    ports:
      - 27017:27017
    volumes:
      - kbase-db-volumen:/data/db
  vtiger-db:
    container_name: 'vtiger-db'
    image: mysql:5.6.23
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}}
      - BASE_URL=${BASE_URL}
    ports:
      - 3306:3306